sudo: false
language: ruby
before_install: gem update --system
cache: bundler
rvm:
  - 2.2
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.2
  - jruby-9.1.6.0

env:
  matrix:
    - RAILS='~> 4.2.0'
    - RAILS='~> 5.0.0'
    - RAILS='~> 5.1.0'
    - RAILS='~> 5.2.0'
    - RAILS='master'

matrix:
  allow_failures:
    - env: RAILS='~> 4.2.0'
      rvm: jruby-9.1.6.0
    - env: RAILS='~> 5.0.0'
      rvm: jruby-9.1.6.0
    - env: RAILS='~> 5.1.0'
      rvm: jruby-9.1.6.0
    - env: RAILS='~> 5.2.0'
      rvm: jruby-9.1.6.0
    - env: RAILS='master'
      rvm: jruby-9.1.6.0
  exclude:
    - rvm: 2.2
      env: RAILS='master'
    - rvm: 2.3.5
      env: RAILS='master'
    - rvm: 2.4.3
      env: RAILS='master'
